# -*- coding: utf-8 -*-
"""faktorial rekursif.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nCX4_S2pjp-faert3bcW92wz0-YXYUo
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n-1)

angka = int(input("Masukkan bilangan: "))
print(f"Faktorial dari {angka} adalah {faktorial(angka)}")
