# -*- coding: utf-8 -*-
"""hitung diskon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nCX4_S2pjp-faert3bcW92wz0-YXYUo
"""

total_belanja = float(input("Masukkan total belanja: Rp"))

if total_belanja > 500000:
    diskon = total_belanja * 0.1
    total_bayar = total_belanja - diskon
    print(f"Selamat! Anda mendapat diskon 10% sebesar Rp{diskon:,.2f}")
else:
    total_bayar = total_belanja
    print("Maaf, Anda belum mendapat diskon")

print(f"Total yang harus dibayar: Rp{total_bayar:,.2f}")