# -*- coding: utf-8 -*-
"""nilai _siswa.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nCX4_S2pjp-faert3bcW92wz0-YXYUo
"""

nilai_siswa = []
for i in range(5):
    nilai = float(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

nilai_tertinggi = max(nilai_siswa)
index_tertinggi = nilai_siswa.index(nilai_tertinggi) + 1

print(f"Nilai tertinggi adalah {nilai_tertinggi} diperoleh oleh siswa ke-{index_tertinggi}")